
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuepgwfnipfmipznbpgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZXBnd2ZuaXBmbWlwem5icGdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjk1MDgsImV4cCI6MjA1OTcwNTUwOH0.TRWTgzaiQuVHF0dBmvhAbqAzh_s80zL4O74FY2Mcgj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'skillswap-auth-storage-key',
  }
});
